project:
  type: website

website:
  title: "`census21api`"
  navbar:
    border: false
    background: light
    foreground: dark
    left:
      - href: index.qmd
        text: About
      - href: docs/tutorials/index.qmd
        text: Tutorials
      - href: docs/reference/index.qmd
        text: Reference
    right:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/datasciencecampus/census21api
          - text: Open an issue
            url: https://github.com/datasciencecampus/census21api/issues
  page-footer:
    left: >
      All content is available under the
      [Open Government Licence V3.0](https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/),
      except where otherwise stated.<br>
      Built using [Quarto](https://quarto.org/).

format:
  html:
    mainfont: Arial
    theme: flatly
    lang: en-GB

quartodoc:
  title: API reference
  package: census21api
  dir: docs/reference
  sections:
    - title: CensusAPI
      desc: Core class for connecting to the Census API.
      package: census21api.wrapper
      contents:
        - CensusAPI
