[project]
name = "census21api"
version = "0.0.1"
dependencies = [
    "requests",
    "typing",
    "tqdm",
    "pre-commit",
    "pandas==2.0.3",
    "tkinter"
]


[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
