name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - "dev*"

jobs:
  test:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.7, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"
      - name: Update pip and install the package
        run: |
          python -m pip install --upgrade pip
          python -m pip install .
      - name: Run tests
        run: |
          python -m pytest tests
